# Airbnb Config: https://www.npmjs.com/package/eslint-config-airbnb
# Airbnb Config for Typescript: https://www.npmjs.com/package/eslint-config-airbnb-typescript
extends:
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  warnOnUnsupportedTypeScriptVersion: true
  project: "./tsconfig.json"
env:
  browser: true
plugins:
  - "@typescript-eslint"
  - "check-file"
ignorePatterns:
  - dist/**/*
rules:
  # When using methods with underscores inside a class, you need to enable this rule
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allowAfterSuper: true
  linebreak-style: 0
  # Sometimes it's more convenient to have named exports even
  # though only one thing has to be exported.
  import/prefer-default-export:
    "off"
    # For Typescript this is needed since it can call out false negatives.
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#how-to-use
  # https://github.com/typescript-eslint/typescript-eslint/issues/2540#issuecomment-692505191
  class-methods-use-this: "off"
  no-use-before-define: "off"
  "@typescript-eslint/type-annotation-spacing": error
  check-file/filename-naming-convention:
    - error
    - "**/*.{jsx,tsx,ts,js,css,sass,svg,jpg,jpeg,png}": "KEBAB_CASE"
    - ignoreMiddleExtensions: true
  check-file/folder-naming-convention:
    - error
    - "src/**/": "KEBAB_CASE"
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "vite.config.*"
        - "**/vite-env.d.ts"
  no-console: "off"

# Allows for absolute imports
settings:
  import/resolver:
    node:
      paths: ["src"]
