export const SceneKeys = {
  BOOT: "BOOT",
  PRELOADER: "PRELOADER",
  MAIN_MENU: "MAIN_MENU",
  LEVELS_MENU: "LEVELS_MENU",
  LEVEL_1: "LEVEL_1",
  LEVEL_2: "LEVEL_2",
  LEVEL_3: "LEVEL_3",
  LEVEL_4: "LEVEL_4",
  LEVEL_5: "LEVEL_5",
  GAME_OVER: "GAME_OVER",
};
