import { AssetKeys } from "./asset-keys";

export const AnimationsKeys = {
  PLAYER_UP: `${AssetKeys.CHARACTERS.PLAYER}_UP_ANIMATION`,
  PLAYER_DOWN: `${AssetKeys.CHARACTERS.PLAYER}_DOWN_ANIMATION`,
  PLAYER_LEFT: `${AssetKeys.CHARACTERS.PLAYER}_LEFT_ANIMATION`,
  PLAYER_RIGHT: `${AssetKeys.CHARACTERS.PLAYER}_RIGHT_ANIMATION`,
  ORANGE: `${AssetKeys.ITEMS.FRUITS.ORANGE}_ANIMATION`,
};
