export const AssetKeys = {
  BACKGROUNDS: {
    MAIN_MENU: "MAIN-MENU-BACKGROUND",
    LEVELS: "LEVELS-BACKGROUND",
  },
  CHARACTERS: {
    PLAYER: "PLAYER",
    NPC: "NPC",
  },
  UI_COMPONENTS: {
    CURSOR: "CURSOR",
    HEALTH_BAR: {
      FILL: "HEALTH_BAR_FILL",
      BACKGROUND: "HEALTH_BAR_BACKGROUND",
    },
    BUTTON_CIRCLE: "BUTTON_CIRCLE",
  },
  TILES: {
    GRASS: "GRASS",
    FLOWER: "FLOWER",
    TREE: "TREE",
    FLOWER_GRASS: "FLOWER_GRASS",
  },
  ITEMS: {
    FRUITS: {
      ORANGE: {
        ASSET_KEY: "ORANGE",
        ANIMATION_KEY: "ORANGE_ANIMATION",
        FRAME_WIDTH: 32,
        FRAME_HEIGHT: 32,
        STAR_FRAME: 0,
        END_FRAME: 17,
      },
      STRAWBERRY: {
        ASSET_KEY: "STRAWBERRY",
        ANIMATION_KEY: "STRAWBERRY_ANIMATION",
        FRAME_WIDTH: 32,
        FRAME_HEIGHT: 32,
        STAR_FRAME: 0,
        END_FRAME: 17,
      },
    },
  },
};
